### ISSUE TITLE
Expcta fails to build on OS X 10.9

### ISSUE THREAD

**Issue by rhyshort** [specta/expecta#150]
When building the latest version of Expecta on  for OS X 10.9 with Cocoapods an error occurs due to the use of `NS_DESIGNATED_INITIALIZER` which is only available on OS X 10.10. The podspec for Expecta indicates it should build on 10.7 and newer.

Compilation output taken from https://github.com/cloudant/CDTDatastore/issues/160

```
In file included from /Users/jimix/work/iOS/CoreData/CDTDatastore/Tests/Pods/Expecta/Expecta/Matchers/EXPMatchers+beCloseTo.m:1:
In file included from /Users/jimix/work/iOS/CoreData/CDTDatastore/Tests/Pods/Expecta/Expecta/Matchers/EXPMatchers+beCloseTo.h:1:
In file included from /Users/jimix/work/iOS/CoreData/CDTDatastore/Tests/Pods/Expecta/Expecta/Expecta.h:10:
In file included from /Users/jimix/work/iOS/CoreData/CDTDatastore/Tests/Pods/Headers/Private/Expecta/ExpectaSupport.h:1:
/Users/jimix/work/iOS/CoreData/CDTDatastore/Tests/Pods/Headers/Private/Expecta/EXPExpect.h:31:159: error: expected ':'
- (instancetype)initWithActualBlock:(id)actualBlock testCase:(id)testCase lineNumber:(int)lineNumber fileName:(const char *)fileName NS_DESIGNATED_INITIALIZER;
                                                                                                                                                              ^
                                                                                                                                                              :
/Users/jimix/work/iOS/CoreData/CDTDatastore/Tests/Pods/Headers/Private/Expecta/EXPExpect.h:43:110: error: expected ':'
- (instancetype)initWithExpectation:(EXPExpect *)expectation selector:(SEL)selector NS_DESIGNATED_INITIALIZER;
```
